site_name: idemeum
site_description: Digital identity for the online world
copyright: Copyright 2021 idemeum
docs_dir: docs-source
site_dir: docs
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: docs-source/material
  language: en
  font:
    text: Inter
    code: Inter
  logo: assets/idemeum-logo.svg
  favicon: assets/idemeum-favicon.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.expand

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - abbr
  - def_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md
  - Intro: intro.md
  - Enterprise idemeum:
    - Overview: enterprise-overview.md
    - IDP integrations:
      - Azure AD (B2B): azuread.md
      - Worspace ONE Access: ws1access.md
      - Okta: okta.md

plugins:
  - search

google_analytics:
  - G-28BFDTM9SP
  - auto

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/channel/UCyPMNEEfPuRlcWVmGKGb6ug
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/idemeum/
