basic_settings:
  site_title: Application Management Platform
  favicon_image: "/assets/img/favicon/idemeum-favicon.png"

header_settings:
  logo_image: /assets/img/logo/idemeum-logo.png
  mobile_logo_image: /assets/img/logo/idemeum-logo.png
  # Choose a color for your header [blue, dark, light].
  theme: blue
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "no"

# Setup your navigation below – how to use the icons:
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket.
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work!
menu_settings:
  menu_items:
  #- title: 'For your customers'
    #submenu_items:
     #- title: 'Passwordless app login'
       #url: /forcustomers
       #icon: ni ni-single-02 text-warning
     #- title: App login demo
       #url: https://jsdemo.idemeum.com
       #icon: ni ni-tv-2 text-success
    # - title: 'Pricing'
       #url: /pricing
       #icon: ni ni-money-coins text-primary
      #- title: Passwordless Device Deployment
       # url: /deployment
        #icon: fa fa-briefcase text-success

  - title: 'Solutions'
    submenu_items:
    - title: Employee IT onboarding
      url: /onboarding
      icon: ni ni-badge text-primary
    #- title: Passwordless Device Deployment
     # url: /deployment
      #icon: fa fa-briefcase text-success
  #- title: 'Resources'
    #submenu_items:
     #- title: Blog
       #url: https://blog.idemeum.com
       #icon: ni ni-books text-warning
     #- title: Docs
       #url: https://docs.idemeum.com
       #icon: ni ni-books text-primary
     #- title: Videos
       #url: /videos
       #icon: ni ni-tv-2 text-info
    #- title: Submit product idea
      #url: 'https://roadmap.idemeum.com/roadmaps/5fb1f2eac80bbc00293063d0/public#ideas'
      #icon: ni-bulb-61 text-primary
  - title: 'Company'
    submenu_items:
    - title: About idemeum
      url: /about
      icon: ni ni-spaceship text-success
    - title: Contact us
      url: /contact
      icon: fa fa-envelope text-warning

footer_settings:
  footer_tagline: Go passwordless with idemeum

contact_settings:
  form_action: 'https://formspree.io/f/mayanwpd'
  confirmation_url: '/thanks'
  email_subject: 'Contact submission FormSpree from idemeum website'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/idemeum'
  twitter_url: 'https://twitter.com/idemeum'
  instagram_url: ''
  youtube_url: 'https://youtube.com/channel/UCyPMNEEfPuRlcWVmGKGb6ug'
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://github.com/idemeum'
  reddit_url: ''
  linkedin_url: 'https://www.linkedin.com/company/idemeum/'

authors:
  Nikolay:
    name: Nikolay
    picture: /assets/img/faces/avatar1.png

advanced_settings:
  analytics_code:
  header_js:
  footer_js:
