basic_settings:
  site_title: idemeum digital identity
  favicon_image: "/assets/img/favicon/idemeum-favicon.png"

header_settings:
  logo_image: /assets/img/logo/idemeum-logo.png
  mobile_logo_image: /assets/img/logo/idemeum-logo.png
  # Choose a color for your header [blue, dark, light].
  theme: blue
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "no"

# Setup your navigation below – how to use the icons:
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket.
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work!
menu_settings:
  menu_items:
    - title: 'Blog'
      url: /blog
    - title: 'Contact'
      url: /contact

footer_settings:
  footer_tagline: idemeum

contact_settings:
  form_action: 'https://formspree.io/f/mnqovleb'
  confirmation_url: '/thanks'
  email_subject: 'Contact submission FormSpree from idemeum website'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: ''
  reddit_url: ''
  linkedin_url: ''

authors:
  tom:
    name: Nikolay
    picture: /assets/img/faces/team-1.jpg

advanced_settings:
  analytics_code:
  header_js:
  footer_js:
