name: Upgrade mkdocs files
on:
  push:
    paths:
    - 'docs/**'
    - '**.yml'
    branches:
    - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pip install mkdocs-material
      - run: git fetch
      - run: mkdocs build
      - run: ls -a
      - run: git status
      - run: git add .
      - run: git commit - m "Adding docuemntation files"
      - run: git push
