name: Upgrade mkdocs files
on:
  push:
    paths:
    - 'docs-source/**'
    branches:
    - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pip install mkdocs-material
      - run: git fetch
      - run: git checkout gh-pages
      - run: mkdocs build --clean
      - run: git add .
      - run: git config --global user.email "nik@idemeum.com"
      - run: git config --global user.name "Nikolay"
      - run: git commit -m "This is a commit triggered by workflow. Updating documentation files."
      - run: git push
